name: Run WebDriverIO Tests

on:
  push:
    branches:
      - main

jobs:
  wdio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run WebDriverIO tests
      run: npm run wdio

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: screenshots
